displayName=RaidParty
author=Kalsupes
support=https://github.com/Kalsupes/RaidParty
description=<html>A party management system which includes ready checks, loot preferences, ping system, and more!</html>
tags=raidparty,queue,party,hub,party panel
plugins=com.github.kalsupes.raidparty.RaidPartyPlugin
build=standard